# Generated by Django 2.1.3 on 2018-11-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181106_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivers',
            fields=[
                ('receiver_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
