# Generated by Django 2.1.3 on 2018-11-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_receivers_receiver_dev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='receiver_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Locations'),
        ),
    ]
