# Generated by Django 2.1.3 on 2018-11-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181106_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receivers',
            new_name='Receiver',
        ),
    ]
