# Generated by Django 2.1.3 on 2018-11-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181106_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comment',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
