# Generated by Django 2.1.3 on 2018-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_location_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('Not defined', 'Not defined'), ('Floor 1', 'Floor 1'), ('Floor 2', 'Floor 2'), ('Floor 3', 'Floor 3')], max_length=16, unique=True),
        ),
    ]
