# Generated by Django 2.1.3 on 2018-11-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_securitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitygroup',
            name='access_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location'),
        ),
    ]
