# Generated by Django 2.1.3 on 2018-11-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_securitygroup_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=256)),
                ('is_active', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='No', max_length=1)),
            ],
        ),
    ]
