# Generated by Django 2.1.3 on 2018-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181106_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nfc_dev_id',
            field=models.CharField(default='00 00 00 00', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
