# Generated by Django 2.1.3 on 2018-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181106_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=8),
        ),
    ]
