# Generated by Django 2.1.3 on 2018-11-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181106_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Employee',
        ),
    ]
