# Generated by Django 2.1.3 on 2018-11-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20181107_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitygroup',
            old_name='group_name',
            new_name='security_group_name',
        ),
    ]
