# Generated by Django 2.1.3 on 2018-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nfc_dev_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
