# Generated by Django 2.1.3 on 2018-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181107_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitygroup',
            name='security_group_name',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
