# Generated by Django 2.1.3 on 2018-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
